name: run

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Updates image
    
    steps:
      - uses: actions/checkout@v2 # checkout the repository content to github runner.
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
        run: |
          python run.py
